### ISSUE TITLE
Excessive HTTP requests triggered on interaction with user input history

### ISSUE THREAD

**Issue by relandboyle** [Linkta-org/core#297]
**Related User Story**

**Related Tickets**

**Acceptance Criteria**

Normal-ish interactions triggered numerous requests to the server and exceeded the configured rate limit during a recent demo session.
Explore the implementation of Tanstack UseInfiniteQuery hook as a possible cause

**Subtasks**
<!-- If necessary, break down the ticket into smaller, actionable subtasks. Create issues accordingly.>

**Comment by ejwoods** [comment]
I’m guessing at least part of this is from React strict mode doubling component mounts - when I ran into this, since the rate limit is 60 requests/15 min, I manually counted out switching between flows 30 times and hit the limiter at the 31st exactly. I then changed the limit to 6 and hit it after viewing 3 flows. I didn’t dig too deep into the code so I’m not sure if this signals a need for refactoring anywhere.

The first thing I'd try in troubleshooting this is running without strict mode and see if there are still any excessive requests.

**Comment by relandboyle** [comment]
@ejwoods @LucieSeidler @kinskiwu I'm planning to close this issue. I believe Kinski resolved the issue we observed last week with numerous duplicate requests. Note: We were seeing varying numbers of duplicate requests, sometimes eight or more at a time. This is very different from consistently seeing two requests.

Hitting the rate limiter during development is normal and expected. We're often behaving in ways that a real user never would.

Seeing two request when deliberately triggering one request is normal and expected due to preflight OPTIONS requests.

Anyone is welcome to propose a higher rate limit than the current 60 per 15 minutes per user. These values are arbitrary and can be changed with a very low standard for justification. If you do change the rate limit, consider making these values into environment variables so they can be set differently for the deployed application.

[HERE](https://httptoolkit.com/blog/cache-your-cors/) is a good article which include describes caching preflight checks in the browsers.
